#!/usr/bin/env python

import sys
import subprocess

commit_msg_filepath = sys.argv[1]

process = subprocess.Popen('git symbolic-ref --short HEAD'.split(), stdout=subprocess.PIPE)
output, error = process.communicate()
if error:
  exit(1)


branch_name = output.upper()
ticket = branch_name

if branch_name.startswith('IMC'):
  ticket = branch_name[:8]


with open(commit_msg_filepath, 'w') as f:
  f.write("%s: " % branch_name)
