#!/usr/bin/env python

import sys
import subprocess

import re

commit_msg_filepath = sys.argv[1]
print(sys.argv)
if '--no-verify' in sys.argv:
  exit(0)

process = subprocess.Popen('git symbolic-ref --short HEAD'.split(), stdout=subprocess.PIPE)
output, error = process.communicate()
if error:
  exit(1)

branch_name = output.strip()
name_match = re.match(r".*(imc_\d+)[_-]*(.*)", branch_name, re.IGNORECASE)

if name_match:
  ticket_number = name_match.group(1)
  ticket_number = re.sub(r"[-_]", '-', ticket_number).upper()
  ticket_sentence = name_match.group(2)
  ticket_sentence = re.sub(r"[-_]", ' ', ticket_sentence).title()
  ticket_full_title = ticket_number + ' - ' + ticket_sentence

with open(commit_msg_filepath, 'r+') as f:
  commit_msg = f.read()
  f.seek(0, 0)
  f.write('%s: \n%s\n' % (ticket_full_title, commit_msg))
